pdf_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Rest Framework auth urls
    url(r'^apiv1/api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # link to test forms app
    url(r'^test_form/', include('test_forms.urls', namespace='test_form')),

]

test_forms/urls.py
# DJANGO imports
from django.conf.urls import url

# LOCAL APP imports
from . import views



urlpatterns = [

    # WIZARD FORM FOR NEW ADDRESS
    url(r'^new_address_form/$', views.IndependentCustomerAddressView.as_view(), name='new-address'),

    # view for creating foreign key relationship
    url(r'^(?P<slug>[\w-]+)/address_check/$', views.InspectionFormView.as_view(), name='address-check'),

    # New form from new address page
    url(r'^(?P<slug>[\w-]+)/new_address_inspection/$', views.new_test_form_wizard_view, name='new-address-form'),

    # FORMSET view
    url(r'^(?P<slug>[\w-]+)/device_tests/$', views.DeviceTestFormsetView.as_view(), name='device-tests'),

    # Test Form Complete 
    url(r'^new_form/test_form_complete/$', views.CompleteFormView, name='complete-form'),
    
    # Address list
    url(r'^addresses/$', views.AddressListView.as_view(), name='address-list'),

    # Test list
    url(r'^(?P<slug>[\w-]+)/$', views.TestListView.as_view(), name='test-list'),

    # Test list
    url(r'^(?P<slug>[\w-]+)/new_form/$', views.test_form_wizard_view, name='test_form_wizard_view'),
   

]

test_forms/models.py
# DJANGO imports
from django.core.urlresolvers import reverse
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify

# PYTHON imports
import datetime
import itertools

#======================================================================================
#=========================== DATA MODELS START HERE ===================================

class CustomerAddress(models.Model):
    
    customer_pk = models.AutoField(primary_key=True)
    address = models.CharField(max_length=1000)
    slug = models.SlugField(max_length=140, unique=True)

    def __str__(self):
        return self.address
 
    def _get_unique_slug(self):
        slug = slugify(self.address)
        unique_slug = slug
        num = 1
        while CustomerAddress.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1
        return unique_slug
 
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super(CustomerAddress, self).save(**kwargs)
        inspection = Inspection(customer_address=self)
        inspection.save()

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('test_form:address-check', kwargs={'slug': self.slug})



class Inspection(models.Model):

    customer_address = models.ForeignKey(CustomerAddress)
    inspection_date = models.DateField(default=datetime.date.today)
    inspection_time = models.TimeField(default=datetime.datetime.now().time())
    slug = models.SlugField(max_length=140, unique=True)

    def _get_unique_slug(self):
        slug = slugify(self.customer_address) + slugify(self.inspection_date)
        unique_slug = slug
        num = 1
        while Inspection.objects.filter(slug=unique_slug).exists():
            
            unique_slug = '{}-{}'.format(slug, num)
            
            num += 1
        return unique_slug

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('test_form:new-address-form', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()
        super(Inspection, self).save(**kwargs)

    def __str__(self):
        return str(self.customer_address)

    # def save(self, *args, **kwargs):
    #     instance = super(Inspection, self).save(*args, **kwargs)
    #     self.customer_address.save()
    #     return instance

        # ALL SECTION MODELS
        # section_list = [Section1, Section2, Section3, Section4_1, Section4_2, Section5, 
        # Section6, Section7_1, Section7_2, Section7_3, Section7_4, Section7_5, Section7_6, 
        # Section7_7, Section7_8, Section7_9, Section8, Section9, Section10_1, Section10_2]

        # # all instance variables
        # section_list_lowercase = ['section1', 'section2', 'section3', 'section4_1', 'section4_2', 'section5',
        # 'section6', 'section7_1', 'section7_2', 'section7_3', 'section7_4',
        # 'section7_5', 'section7_6', 'section7_7', 'section7_8', 'section7_9', 'section8',
        # 'section9', 'section10_1', 'section10_2']
        
        # # SET ALL SECTION MODELS FOREIGN KEY
        # # RELATIONSHIP WITH INSPECTION
        # for section, section_lowercased in zip(section_list, section_list_lowercase):
        #     section_lowercased = section(inspection=self)
        #     section_lowercased.save()

    
        #section1 = Section1(inspection=self)
        #section1.save()

    # def __unicode__(self):

    #     return unicode(self.customer_address)



    # # ==============================================================================
    # @receiver(post_save,sender=CustomerAddress)
    # def my_handler(sender,instance,**kwargs):
    #     p=Inspection(customer_address_id=instance.customer_pk)
    #     p.save()
    # ==============================================================================


class Section1(models.Model):
    
    inspection = models.ForeignKey(Inspection)
    property_name = models.CharField(max_length=10000)
    property_address = models.CharField(max_length=10000)
    property_description = models.CharField(max_length=10000)
    property_representative = models.CharField(max_length=10000)
    pr_address = models.CharField(max_length=10000)
    pr_phone = models.CharField(max_length=10)
    pr_fax = models.CharField(max_length=10)
    pr_email = models.EmailField()
    authority_with_jurisdiction = models.CharField(max_length=10000)
    aj_phone = models.CharField(max_length=10)
    aj_fax = models.CharField(max_length=10)
    aj_email = models.EmailField()

    def __str__(self):
        admin_name = str(self.inspection) + '-section1'
        return admin_name

    def save(self, *args, **kwargs):
        instance = super(Section1, self).save(*args, **kwargs)
        self.inspection.save()
        return instance

class Section2(models.Model):

    inspection = models.ForeignKey(Inspection)
    org_test_service = models.CharField(max_length=10000)
    ots_address = models.CharField(max_length=10000)
    ots_address = models.CharField(max_length=10000)
    ots_phone = models.CharField(max_length=10)
    ots_fax = models.CharField(max_length=10)
    ots_email = models.EmailField()
    service_technician = models.CharField(max_length=10000)
    test_frequency = models.CharField(max_length=250)
    monitor_org = models.CharField(max_length=10000)
    mo_address = models.CharField(max_length=10000)
    mo_phone = models.CharField(max_length=10)
    mo_fax = models.CharField(max_length=10)
    mo_email = models.EmailField()

    def __str__(self):
        admin_name = str(self.inspection) + '-section2'
        return admin_name

    def save(self, *args, **kwargs):
        instance = super(Section2, self).save(*args, **kwargs)
        self.inspection.save()
        return instance

class Section3(models.Model):

    inspection = models.ForeignKey(Inspection)
    fas_nonvoice = models.BooleanField(default=False)
    evacs = models.BooleanField(default=False)
    mns = models.BooleanField(default=False)
    system_combo = models.BooleanField(default=False)
    fas_nonvoice_combo = models.BooleanField(default=False)
    evacs_combo = models.BooleanField(default=False)
    mns_combo = models.BooleanField(default=False)
    two_way_combo = models.BooleanField(default=False)
    other = models.BooleanField(default=False)
    specify = models.CharField(max_length=10000, null=True, blank=True)
    manufacturer = models.CharField(max_length=255)
    model_number = models.CharField(max_length=255)
    sys_docs = models.BooleanField(default=False)
    sys_docs_location = models.CharField(max_length=500, null=True, blank=True)
    site_specific_software = models.BooleanField(default=False)
    revision_number = models.CharField(max_length=255, null=True, blank=True)
    last_update = models.DateField(default=None, null=True, blank=True)
    site_software_copy = models.BooleanField(default=False)
    copy_location = models.CharField(max_length=10000, null=True, blank=True)

    def __str__(self):
        admin_name = str(self.inspection) + '-section3'
        return admin_name

    def save(self, *args, **kwargs):
        instance = super(Section3, self).save(*args, **kwargs)
        self.inspection.save()
        return instance

class Section4_1(models.Model):

    inspection = models.ForeignKey(Inspection)
    cp_input_voltage = models.FloatField(max_length=255)
    cp_amps = models.FloatField(max_length=255)
    generator = models.BooleanField(default=False)
    generator_location = models.CharField(max_length=10000, null=True, blank=True)
    generator_fuel_location = models.CharField(max_length=500, null=True, blank=True)
    generator_fuel_type = models.CharField(max_length=255, null=True, blank=True)
    ups = models.BooleanField(default=False)
    ups_powered_equipment = models.CharField(max_length=10000, null=True, blank=True)
    ups_location = models.CharField(max_length=10000, null=True, blank=True)
    ups_battery_standby = models.FloatField(max_length=255, null=True, blank=True)
    ups_battery_alarm = models.FloatField(max_length=255, null=True, blank=True)
    battery_location = models.CharField(max_length=100)
    battery_type = models.CharField(max_length=100)
    battery_voltage = models.FloatField(max_length=100)
    battery_amp_hour = models.CharField(max_length=100)
    battery_standby = models.FloatField(max_length=100)
    battery_alarm = models.FloatField(max_length=100)
    battery_mark = models.BooleanField(default=False)

    def __str__(self):
        admin_name = str(self.inspection) + '-section4_1'
        return admin_name

    def save(self, *args, **kwargs):
        instance = super(Section4_1, self).save(*args, **kwargs)
        self.inspection.save()
        return instance

class Section4_2(models.Model):

    inspection = models.ForeignKey(Inspection)
    power_extender_panels = models.BooleanField(default=False)
    pep_voltage = models.FloatField(max_length=255, null=True, blank=True)
    pep_amps = models.FloatField(max_length=255, null=True, blank=True)
    generator = models.BooleanField(default=False)
    generator_location = models.CharField(max_length=10000, null=True, blank=True)
    generator_fuel_location = models.CharField(max_length=500, null=True, blank=True)
    generator_fuel_type = models.CharField(max_length=255, null=True, blank=True)
    ups = models.BooleanField(default=False)
    ups_powered_equipment = models.CharField(max_length=10000, null=True, blank=True)
    ups_location = models.CharField(max_length=10000, null=True, blank=True)
    ups_battery_standby = models.FloatField(max_length=255, null=True, blank=True)
    ups_battery_alarm = models.FloatField(max_length=255, null=True, blank=True)
    battery_location = models.CharField(max_length=100)

test_forms/forms.py
import itertools

# DJANGO import
from django import forms
from django.forms import modelformset_factory
from django.utils.text import slugify

# LOCAL APP import
from . import models

#===========================================================================
from django.core.urlresolvers import reverse
from django.utils.safestring import mark_safe
from django.forms import widgets
from django.conf import settings

class RelatedFieldWidgetCanAdd(widgets.Select):

    def __init__(self, related_model, related_url='test_form:new-address', *args, **kw):

        super(RelatedFieldWidgetCanAdd, self).__init__(*args, **kw)

        if not related_url:
            rel_to = related_model
            info = (rel_to._meta.app_label, rel_to._meta.object_name.lower())
            related_url = 'admin:%s_%s_add' % info

        # Be careful that here "reverse" is not allowed
        self.related_url = related_url

    def render(self, name, value, *args, **kwargs):
        self.related_url = reverse(self.related_url)
        output = [super(RelatedFieldWidgetCanAdd, self).render(name, value, *args, **kwargs)]
        output.append(u'<a href="%s" class="add-another" id="add_id_%s" onclick="return showAddAnotherPopup(this);"> ' % \
            (self.related_url, name))
        output.append(u'<img src="%sadmin/img/icon_addlink.gif" width="10" height="10" alt="%s"/></a>' % (settings.STATIC_URL, ('Add New Address')))                                                                                                                               
        return mark_safe(u''.join(output))

#===========================================================================

class NewCustomerAddressForm(forms.ModelForm):

    class Meta:
        model = models.CustomerAddress
        fields = [
            'address',
        ]

# ==========================================================================

class InspectionForm(forms.ModelForm):

    class Meta:
        model = models.Inspection
        fields = [
           'customer_address',
        ]

    # the request is now available, add it to the instance data
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(InspectionForm, self).__init__(*args, **kwargs)

#===========================================================================

class CustomerAddressForm(forms.ModelForm):

    address = forms.ModelChoiceField(
       required=True,
       queryset=models.CustomerAddress.objects.all(),
       widget=RelatedFieldWidgetCanAdd(models.CustomerAddress)
    )

    class Meta:
        model = models.CustomerAddress
        fields = [
            'address',
        ]

    # def __init__(self, *args, **kwargs):
    #     super(models.CustomerAddress, self.).save(**kwargs)
    #     inspection = models.Inspection(customer_address=self)
    #     inspection.save()
    


class Section1Form(forms.ModelForm):

    class Meta:
        model = models.Section1
        exclude = [
            'inspection',
        ]

class Section2Form(forms.ModelForm):

    class Meta:
        model = models.Section2
        exclude = [
            'inspection',
        ]

class Section3Form(forms.ModelForm):

    class Meta:
        model = models.Section3
        exclude = [
            'inspection',
        ]

class Section4_1Form(forms.ModelForm):

    class Meta:
        model = models.Section4_1
        exclude = [
            'inspection',
        ]

class Section4_2Form(forms.ModelForm):

    class Meta:
        model = models.Section4_2
        exclude = [
            'inspection',
        ]

class Section5Form(forms.ModelForm):

    class Meta:
        model = models.Section5
        exclude = [
            'inspection',
        ]

class Section6Form(forms.ModelForm):

    class Meta:
        model = models.Section6
        exclude = [
            'inspection',
        ]

class Section7_1Form(forms.ModelForm):

    class Meta:
        model = models.Section7_1
        exclude = [
            'inspection',
        ]

class Section7_2Form(forms.ModelForm):

    class Meta:
        model = models.Section7_2
        exclude = [
            'inspection',
        ]

class Section7_3Form(forms.ModelForm):

    class Meta:
        model = models.Section7_3
        exclude = [
            'inspection',
        ]  

class Section7_4Form(forms.ModelForm):

    class Meta:
        model = models.Section7_4
        exclude = [
            'inspection',
        ]

class Section7_5Form(forms.ModelForm):

    class Meta:
        model = models.Section7_5
        exclude = [
            'inspection',
        ]
class Section7_6Form(forms.ModelForm):

    class Meta:
        model = models.Section7_6
        exclude = [
            'inspection',
        ]

class Section7_7Form(forms.ModelForm):

    class Meta:
        model = models.Section7_7
        exclude = [
            'inspection',
        ]

class Section7_8Form(forms.ModelForm):

    class Meta:
        model = models.Section7_8
        exclude = [
            'inspection',
        ]

device_test_formset = modelformset_factory(
    models.Section7_8,
    form=Section7_8Form,
    extra=20,
    )

#formset = device_test_formset(queryset=models.Section7_8.objects.none())

class Section7_9Form(forms.ModelForm):

    class Meta:
        model = models.Section7_9
        exclude = [
            'inspection',
        ]

class Section8Form(forms.ModelForm):

    class Meta:
        model = models.Section8
        exclude = [
            'inspection',
        ]

class Section9Form(forms.ModelForm):

    class Meta:
        model = models.Section9
        exclude = [
            'inspection',
        ]

class Section10_1Form(forms.ModelForm):

    class Meta:
        model = models.Section10_1
        exclude = [
            'inspection',
        ]

class Section10_2Form(forms.ModelForm):

    class Meta:
        model = models.Section10_2
        exclude = [
            'inspection',
        ]

test_forms/templates/test_forms/address_check.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            
                <h1>{{ title }}</h1>
                <h1>hello</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-group">
                        <input class="form-control" type="submit" value="Save" />
                    </div>
                </form> 
            
        </div>
    </div>
</div>
{% endblock %}

test_forms/templates/test_forms/address_detail.html
{% extends 'base.html' %}
{% block title %}{{ object.address }}{% endblock %}
{% block body %}
<ul>
    {% for test_date in inspection_dates %}
        <li>Test date: {{ test_date }}</li>
    {% endfor %}
</ul>
<h1></h1>
<h2>
    <a href="{% url 'test_form:test_form_wizard_view' %}">New Test</a>
</h2>
{% endblock %}

test_forms/templates/test_forms/address_list.html
{% extends 'base.html' %}
{% block body %}
<h1>Addresses</h1>
    <ul>
        {% for client in client_list %}
            
            <li><a href="{% url 'test_form:test-list' client.slug %}">{{ client.address }}</a></li>
            <ul>
                <li><a href="{% url 'test_form:test_form_wizard_view' client.slug %}">New form (pre-populated)</a></li>
                <li><a href="{% url 'test_form:address-check' client.slug %}">New form (no data)</a></li>
            </ul>
        {% empty %}
            <li>No articles yet.</li>
        {% endfor %}
    </ul>

{% endblock %}

test_forms/templates/test_forms/done.html
{% extends 'base.html' %}
{% block body %}
<h1>Thanks!</h1>
{% for form in form_data %}
    {{ form }}
{% endfor %}
{% endblock %}

test_forms/templates/test_forms/section.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            
                <h1>{{ title }}</h1>
                <h1>hello</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <div class="form-group">
                        <input class="form-control" type="submit" value="Save" />
                    </div>
                </form> 
            
        </div>
    </div>
</div>
{% endblock %}

test_forms/templates/test_forms/test_form_complete.html
{% extends 'base.html' %}
{% block body %}
<h1>Thanks!</h1>
{% for form in form_data %}
    {{ form }}
{% endfor %}
{% endblock %}

test_forms/templates/test_forms/test_list.html
{% extends 'base.html' %}
{% block body %}
<h1>tests</h1>


    <ul>
        {% for inspection in inspection_list %}
            
            <li><a href="{% url 'test_form:test_form_wizard_view' slug=inspection.slug %}">New test with data from test date: {{ inspection.inspection_date }}</a></li>
            <li><a href="{% url 'test_form:new-address-form' slug=inspection.slug %}">New test (no data)</a></li>
            
        {% empty %}
            <li>No tests yet.</li>
        {% endfor %}
    </ul>

{% endblock %}

test_forms/templates/test_forms/test_wizard_form.html
{% extends 'base.html' %}
{% block title %}Client Form{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-offset-3 col-md-6">
            <h1>George Alarm test form</h1>
            <p>Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }} </p>
            <form method="post">
                {% csrf_token %}
                {{ wizard.management_form }}
                {% if wizard.form.forms %}
                    {{ wizard.form.management_form }}
                    {% for form in wizard.form.forms %}
                        {{ form.as_p }}
                        <table>
                            {{ formset }}
                        </table>
                    {% endfor %}
                {% else %}
                    {{ wizard.form.as_p }}
                {% endif %}
                
                <div class="form-group">
                    <input class="form-control" type="submit" value="Save" />
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}