pdf_proj/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # Rest Framework auth urls
    url(r'^apiv1/api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # link to test forms app
    url(r'^test_form/', include('test_forms.urls', namespace='test_form')),

]

test_forms/urls.py
# DJANGO imports
from django.conf.urls import url

# LOCAL APP imports
from . import views



urlpatterns = [

    # WIZARD FORM FOR NEW ADDRESS
    url(r'^new_address_form/$', views.IndependentCustomerAddressView.as_view(), name='new-address'),

    # view for creating foreign key relationship
    url(r'^(?P<slug>[\w-]+)/address_check/$', views.InspectionFormView.as_view(), name='address-check'),

    # New form from new address page
    url(r'^(?P<slug>[\w-]+)/new_address_inspection/$', views.new_test_form_wizard_view, name='new-address-form'),

    # FORMSET view
    url(r'^(?P<slug>[\w-]+)/device_tests/$', views.DeviceTestFormsetView.as_view(), name='device-tests'),

    # Test Form Complete 
    url(r'^new_form/test_form_complete/$', views.CompleteFormView, name='complete-form'),
    
    # Address list
    url(r'^addresses/$', views.AddressListView.as_view(), name='address-list'),

    # Test list
    url(r'^(?P<slug>[\w-]+)/$', views.TestListView.as_view(), name='test-list'),

    # Test list
    url(r'^(?P<slug>[\w-]+)/new_form/$', views.test_form_wizard_view, name='test_form_wizard_view'),
   

]

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load staticfiles %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <!-- Custom CSS -->
        <link rel="stylesheet" type="text/css" href="{% static base_style.css %}">
        
        <title>
            {% block title %}{% endblock %}
        </title>
    </head>
    <body>
        <!-- nav menu -->
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'test_form:address-list' %}">Address List</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp;
                            </a>
                        </li>
                        <li class="">
                            <a href="{% url 'test_form:new-address' %}">
                                New Address
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
        {% block body %}
        {% endblock %}
    </body>
</html>